assign_test:
  extends:
    - .rules:assign_test:target_test-weekend_test
  tags:
    - assign_test
  image: $CI_DOCKER_REGISTRY/ubuntu-test-env$BOT_DOCKER_IMAGE_TAG
  stage: assign_test
  # gitlab ci do not support match job with RegEx or wildcard now in dependencies.
  # we have a lot build example jobs. now we don't use dependencies, just download all artifacts of build stage.
  dependencies: # Here is not a hard dependency relationship, could be skipped. so we do not use "needs" here.
    - build_esp_idf_tests_cmake_esp32
    - build_esp_idf_tests_cmake_esp32s2
    - build_esp_idf_tests_cmake_esp32c3
  variables:
    CI_TARGET_TEST_CONFIG_FILE: "$CI_PROJECT_DIR/tools/ci/config/target-test.yml"
    SUBMODULES_TO_FETCH: "components/esptool_py/esptool"
    EXAMPLE_TEST_DIR: "${CI_PROJECT_DIR}/examples"
    CUSTOM_TEST_DIR: "${CI_PROJECT_DIR}/tools/test_apps"
    UNIT_TEST_DIR: "${CI_PROJECT_DIR}/components/idf_test/unit_test"
    # COMPONENT_UT_DIRS is set by `set_component_ut_vars` in `utils.sh`
    COMPONENT_UT_OUTPUT_DIR: "${CI_PROJECT_DIR}/component_ut"
  artifacts:
    paths:
      - components/idf_test/*/CIConfigs
      - $EXAMPLE_TEST_DIR/test_configs
      - $CUSTOM_TEST_DIR/test_configs
      - $COMPONENT_UT_OUTPUT_DIR/test_configs
      - build_examples/artifact_index.json
      - build_test_apps/artifact_index.json
      - build_component_ut/artifact_index.json
      - tools/unit-test-app/builds/artifact_index.json
    expire_in: 1 week
  script:
    - set_component_ut_vars
    - python tools/ci/python_packages/ttfw_idf/IDFAssignTest.py example_test $EXAMPLE_TEST_DIR -c $CI_TARGET_TEST_CONFIG_FILE -o $EXAMPLE_TEST_DIR/test_configs
    - python tools/ci/python_packages/ttfw_idf/IDFAssignTest.py custom_test $CUSTOM_TEST_DIR -c $CI_TARGET_TEST_CONFIG_FILE -o $CUSTOM_TEST_DIR/test_configs
    - python tools/ci/python_packages/ttfw_idf/IDFAssignTest.py component_ut $COMPONENT_UT_DIRS -c $CI_TARGET_TEST_CONFIG_FILE -o $COMPONENT_UT_OUTPUT_DIR/test_configs
    - python tools/ci/python_packages/ttfw_idf/IDFAssignTest.py unit_test $UNIT_TEST_DIR -c $CI_TARGET_TEST_CONFIG_FILE -o $UNIT_TEST_DIR/CIConfigs
